### ISSUE TITLE
ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by andrewkykoo** [andrewkykoo/react#4]
Browser console tab shows the following message: 

<img width="251" alt="Screenshot 2023-02-15 at 11 38 58 PM" src="https://user-images.githubusercontent.com/47183818/219270306-1bbc90a7-3c82-4be7-b2d0-38c58433f84b.png">

we should look into the doc and use createRoot

**Comment by vaibhavpatidar522** [comment]
ok i will fix these issue please assign me this issue i will update to react 18 and will fix this issue

**Comment by andrewkykoo** [comment]
Hi @vaibhavpatidar522, I have assigned you to this issue. Let's set Thursday (2/23) as the deadline. Thanks!
